### PR TITLE
Version 5.0

### PR DESCRIPTION
**Pull request by alexaubry**
In this version, we add support for the Swift Package Manager. To make these changes possible, we decided to make the following breaking changes:

- Require iOS 11
- Remove the possibility to create items in Objective-C

We are planning to release this version on October 25, 2020. During the next month, please reply to this PR with feedback about any bugs or request.

To use the release candidate version, please use the following tag in your package manager: `5.0.0-rc.2`

### CODE REVIEW

**Comment by rodmaz** [comment]
How come is this even tagged as *release candidate*? 
The Swift Package does not even compile! BTW, my project has target iOS 13.0.

Screen Shot 2020-09-26 at 15 46 23

**Comment by alexaubry** [comment]
> How come is this even tagged as _release candidate_?
> The Swift Package does not even compile! BTW, my project has target iOS 13.0.
> 
> Screen Shot 2020-09-26 at 15 46 23

Thanks for your constructive feedback! As you can see, @ollitapa already fixed it in `develop`, I’m just gonna wait a couple more days before tagging a second version, in case more things come up.

**Comment by eminisrafil** [comment]
Thanks for maintaining this repo!

**Comment by aaronbrethorst** [comment]
Hey Alex - Thanks for getting SPM working! I'd love to be able to move this dependency off Carthage and onto SPM. Any chance you could tag RC 2 today?

**Comment by alexaubry** [comment]
@aaronbrethorst Done!

**Comment by aaronbrethorst** [comment]
Thank you!

**Comment by rodmaz** [comment]
Has anyone tested this? It does not seem like it works properly (at least not on Xcode 12.1). Package does not compile.
Tested from `main` branch and version `5.0.0`.
```
error: Multiple commands produce '/MyCode/MyProject-ezhoowqbocgzhycfoojnfdfrulyf/Build/Intermediates.noindex/BLTNBoard.build/Debug-iphoneos/BLTNBoard.build/Objects-normal/arm64/BLTNBoard.swiftmodule':
1) Target 'BLTNBoard' (project 'BLTNBoard') has compile command for Swift source files
2) Target 'BLTNBoard' (project 'BLTNBoard') has compile command for Swift source files
```

**Comment by ollitapa** [comment]
I've been using the package and it works fine for me. I think the error you are seeing is because you have included the SPM module in two or more Xcode style ".framework" modules. This is a "known" limitation in Xcode and to work around it, you need to make an umbrella ".framework" for your common SPM modules and import that in both of your own modules.

**Comment by rodmaz** [comment]
@ollitapa It is in fact a framework but all other SPM packages in the framework just work perfectly. 

Screen Shot 2020-11-03 at 09 42 10

**Comment by ollitapa** [comment]
Hmm, maybe you have some Carthage/CocoaPods leftovers? Some copy-frameworks step? At least my umbrella framework builds fine.
Screenshot 2020-11-05 at 11 54 12

**Pull request merged**
