### PR TITLE
Fix for iPad split view bug

### PR DESCRIPTION
**Pull request by Piidro**
### Checklist
- [x] I've tested my changes.
- [x] I've read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I've updated the documentation if necessary.

### Motivation and Context
This fixes the issue #172 
Changes were tested with the example application provided.

### Description
Fix was done by setting the correct frame in the `BulletinPresentationAnimationController` when animating the view in. Also fixed couple activity indicator style deprecation warnings.

### CODE REVIEW

**Comment by arguiot** [comment]
@alexaubry after testing it in my own app, this PR fixes the problem.

**Comment by arguiot** [comment]
@a2 @alexaubry Any update?

**Comment by Overlord21** [comment]
I am also facing the same issue with split view and dismiss animation, and wanted to know when will this be merged or should I use the specific branch in the meantime

**Comment by arguiot** [comment]
@Overlord21 since @alexaubry hasn't merged this PR, I'm using @Piidro 's fork in production. I know it's not ideal, but it's the only solution right now.

**Comment by alexaubry** [comment]
Hi here, sorry for the delay merging this, had to deal with other problems. Will make a new release.

**Comment by alexaubry** [comment]
The fix was released in 4.1.1, thanks for your patience.

**Pull request merged**
