### PR TITLE
Add workaround to allow static library usage

### LINKED ISSUE #99: Cannot be built as static library
**Problem Description:**
When using [Cocoapods new static library feature](http://blog.cocoapods.org/CocoaPods-1.5.0/) in a Podfile including BulletinBoard, the build fails due to includes of `BLTNBoard/BLTNBoard-Swift.h` in both `BLTNActionItem.m` & `BLTNPageItem.m` which cannot be found.

I already used a [known workaround](https://github.com/CocoaPods/CocoaPods/issues/7594) which fixes this issue by replacing `BLTNBoard/BLTNBoard-Swift.h` with `BLTNBoard-Swift.h`.

**Steps to reproduce:**
 1. Create a new Xcode project
 2. `pod init`
 3. Remove `use_frameworks!` from `Podfile`
 4. Add `use_modular_headers!` to `Podfile`
 5. `pod install`
 6. Build workspace
 7. 💥

**Environment:**
 - Xcode 9
 - Cocoapods 1.5.3
 - Version of BulletinBoard: 2.0.1

### PR DESCRIPTION
**Pull request by slashmo**
### Checklist
- [x] I've tested my changes.
- [x] I've read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I've updated the documentation if necessary.

### Motivation and Context
I used the workaround mentioned in #99 to allow `BulletinBoard` to be used as a **static library** through Cocoapods. I tested `BulletinBoard` with this PR as both dynamic & static library.

### Description
Somehow, static libraries in Cocoapods cannot find `BLTNBoard-Swift.h` if it's imported with a namespace (`#import <BLTNBoard/BLTNBoard-Swift.h>`) as used in both `BLTNActionItem.m` & `BLTNPageItem.m`. By omitting the namespace the library can be used statically, but not dynamically anymore. That's why I included a check for `BLTNBoard-Swift.h` before importing, which I discovered [here](https://github.com/mxcl/PromiseKit/issues/825).

Closes #99

### CODE REVIEW

**Comment by slashmo** [comment]
Great suggestion, didn’t think of that! 👌 I’ll change it later today.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slashmo** [comment]
@alexaubry Could you please assist me in this? I'm not sure why [Travis fails](https://travis-ci.com/slashmo/BulletinBoard/builds/80004603) since I added the new header file. Locally, I can build both examples.

**Comment by alexaubry** [comment]
@slashmo I investigated and pushed the fix. Basically the support header was included in the public CocoaPods headers, which was causing the build failure. Moving it to the private headers fixes the problem. 

Thanks again for finding the solution!

**Comment by stevenp** [comment]
Can you please release this?

**Pull request merged**
