### PR TITLE
Corner radius and matches iPhone X

### PR DESCRIPTION
**Pull request by CaliCastle**
### Checklist
- [x] I've tested my changes.
- [x] I've read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I've updated the documentation if necessary.

### Motivation and Context
More customization for more controls and who doesn't love customization, right?

### Description
1. Changed font sizes properties from `let` to `var`, making them alterable so users can define font size on their own
2. Added `actionButtonCornerRadius` and `alternativeButtonCornerRadius` for appearance in page items, `cardCornerRadius` for the bulletin card corner radius. (All default to `12`)

Example use:
```swift
/// Card corner radius
bulletinManager.cardCornerRadius = 20
bulletinManager.prepare()
bulletinManager.presentBulletin(above: self)

/// Action button corner radius, make it rounder
page.appearance.actionButtonCornerRadius = 18
```

3. Make bulletin cards rounder and match more like when AirPods card shows up for iPhone X. (Default corner radius of `34`, I know it's a lot but it does look good with the rounded edges on iPhone X)

Screenshots:
This is what AirPods pairing looks like in iPhone X:
img_0194

If user does not define `cardCornerRadius` before calling `prepare` on manager:
img_0195
img_0196

### CODE REVIEW

**Comment by CaliCastle** [comment]
One thing to mention is that running in `iPhone X Simulator` will not get the same result because of the extension for `UIDevice` has limitations.

**Comment by CaliCastle** [comment]
1. Now when the status bar updates, it will animate to the new state instead of jumping without transitions.

2. There are 3 types of bulletin size now: `Compact`, `Regular` and `Full` for size variant controls

**Comment by CaliCastle** [comment]
1. Able to hide bottom (footer) view for safe area in iPhone X to get the matching card like AirPods pairing:
messages image 2986372086

2. Fix iPhone X corner radius to `36` not `34`

**Comment by CaliCastle** [comment]
Hi @alexaubry 

Thanks again for this awesome library!
I hope these changes might do some good to you, just a couple of customization controls I think would be better to have so I added them.

**Comment by alexaubry** [comment]
Thank you @CaliCastle for these updates! The goal for BulletinBoard it to integrate seamlessly with the system, so it's amazing to have it look better on iPhone X 💯

I will be reviewing your changes, thanks again 😃

**Comment by alexaubry** [comment]
I've made some changes to the implementation:

- Detect iPhone X with safe area insets (supports future devices and Simulator)
- Dynamically calculate corner radius when safe insets changes
- Add option to remove padding completely (à la App Store payment view controller)
- Update keyboard animation to support custom padding
- Refine documentation and API to blend in library

If you have any feedback on these changes, feel free to share 😃

Your PR will ship with the next version of the library. Thanks for working on these improvements, good job! 🚀

**Comment by CaliCastle** [comment]
Awesome! Now it’s more configurable, love it!

**Comment by Pomanks** [comment]
Hey guys, I can't find where to disable the bottom safeArea spacing for the presented BLTNItemManager.. ?

**Pull request merged**
