### PR TITLE
Enhance Appearance API

### PR DESCRIPTION
**Pull request by alexaubry**
### Motivation and Context

This PR introduces a new Appearance API that is more flexible, open and customizable.

It allows:

- Full customization of the colors
- Full customization of the font families

Feature request: #18

### Description

The new API is organized around two new classes: `BulletinAppearance` and `BulletinInterfaceBuilder`.

`BulletinAppearance` is an open class that exposes all the properties needed for color and font customization. An object of this class is created for every `PageBulletinItem` at initialization (available via the `appearance` property).

`BulletinInterfaceBuilder` is an open class that contains all the methods needed to generate standard interface components. `PageBulletinItem` creates and uses an object of this type in the `makeArrangedSubviews` method. To customize the type of interface builder to use, 
users can change the `InterfaceBuilderType` property.

### Example

~~~swift
let page = PageBulletinItem(title: "Welcome to MyApp")
page.InterfaceBuilderType = MyCustomBulletinInterfaceBuilder.self
page.appearance.titleFontDescriptor = UIFontDescriptor(name: "AvenirNext-Medium", matrix: .identity)
page.appearance.actionButtonColor = .red
~~~

### CODE REVIEW

**Comment by CaliCastle** [comment]
This is exactly what I wanted! Thanks!
(Typo in the Example where you wrote name: "AvenirNext-Medium)
Great library to work with!

**Comment by alexaubry** [comment]
Thank you!

**Comment by Eliaschetouani** [comment]
Can you explain how can Change the font please, your example is not clear 
Thanks you

**Comment by alexaubry** [comment]
@Eliaschetouani To customize the font, you can use these properties when creating a `PageBulletinItem`:

- `appearance.titleFontDescriptor` to change the title text font
- `appearance.descriptionFontDescriptor` to change the description text font
- `appearance.buttonFontDescriptor` to change the font of button titles

You must assign these properties a `UIFontDescriptor` object that describes the font to use.

Here's a commented version of the example above:

~~~swift
// 1) Create a page bulletin item
let page = PageBulletinItem(title: "Welcome to MyApp")

// 2) Create the font descriptor for the Avenir Next font with a medium weight
let customFontDescriptor = UIFontDescriptor(name: "AvenirNext-Medium", matrix: .identity)

// 3) Set the custom title font
page.appearance.titleFontDescriptor = page.appearance.actionButtonColor = .red
~~~

Hope this helps!

**Pull request merged**
